
const ACTIVITY_STORAGE_KEY = '@activities';
const TIME_STORAGE_KEY = '@time';
const APP_STATE_CHANGED_TIMESTAMP_STORAGE_KEY = '@appStateChangedTimeStamp';
const IS_PAUSED_STORAGE_KEY = '@isPaused';

export {
    ACTIVITY_STORAGE_KEY,
    TIME_STORAGE_KEY,
    APP_STATE_CHANGED_TIMESTAMP_STORAGE_KEY,
    IS_PAUSED_STORAGE_KEY
};
